### ISSUE TITLE
Migrate timestamps to int64_t

### ISSUE THREAD

**Issue by Sv3n** [ravenrd/DRAMPower#10]
(Put here as a reminder, it came up in an email earlier)

**Comment by Sv3n** [comment]
We don't rely on double's anymore to represent time. I propose to remove the getTime() function from MemCommand in favor of the ` int64_t getTimeInt64() const;` function we now use.

https://github.com/ravenrd/DRAMPower/blob/master/src/MemCommand.h#L117

Any objections? If not, then I'll make this change and close the issue in 2 days.

**Comment by myzinsky** [comment]
I think that is totally valid. @efzulian, what do you think?

**Comment by efzulian** [comment]
Hi guys, just wondering why not to use unsigned timestamps (uint64_t instead of int64_t). :)

**Comment by Sv3n** [comment]
Using unsigned numbers creates a few interesting opportunities for failure:
```c++
// If all of these variables are unsigned, then we might end up with
// an unexpectedly large value for 'a'
uint64_t a = max(zero, c-d);
```
The google style guide also agrees to some extent:
https://google.github.io/styleguide/cppguide.html#Integer_Types

**Comment by myzinsky** [comment]
Since we had this afternoon some discussions about using double or int for representing time in SystemC for DRAMSys, I'm curious to know: @Sv3n what is your motivation to represent time in int instead of double?

**Comment by Sv3n** [comment]
The input to DRAMPower is commands, which happen at integer multiples of the clock period. Expressing time as an integer number of clock cycles allows us to write down exactly when a command happens. Arithmetic on these clock cycles is guaranteed to produce an output that is another integer multiple of the clock period. With doubles you cannot guarantee that:

```c++
double now  = current_time_cycles_to_double(0);
double eight_cycles_ago = now - 8;
double four_cycles_ago =  now - 4;

// Now any of these expressions might be true, depending
// on the particular value of 'now':
eight_cycles_ago + 4 == four_cycles_ago;
eight_cycles_ago + 4 > four_cycles_ago;
eight_cycles_ago + 4 < four_cycles_ago;
```

At extremely large values, certain integer values can no longer be expressed in a double, and they will alias to other integers. For a demonstration of the effect (with less waiting time), you can use the smaller 'float' type:

```c++
for (float i = 0; i < 0xFFFFFFFF; i++) {

}

**Comment by myzinsky** [comment]
Thank you for that nice explanation. I had similar concerns, especially the rounding in the high dynamic ranges.
