### ISSUE TITLE
DDR4 and LPDDR3 issues regarding two Voltage Domains and Termination

### ISSUE THREAD

**Issue by myzinsky** [ravenrd/DRAMPower#27]
Hi,

I discovered that DDR4 is not listet in the function hasTwoVoltageDomains in MemorySpecification.h

```c++ 
 bool hasTwoVoltageDomains() const
  {
    return val == LPDDR ||
           val == LPDDR2 ||
           val == LPDDR3 ||
           val == WIDEIO_SDR;
  }
```
Furthermore, LPDDR3 has also termination and is not listed here:

```c++
  bool hasTermination() const
  {
    return val == DDR2 ||
           val == DDR3 ||
           val == DDR4;
  }
```

Is that assumption correct? Or do I get something wrong?

Regards
Matthias

**Comment by Sv3n** [comment]
Good spot! The voltage domain is a bug that I introduced in a fairly old commit:
https://github.com/ravenrd/DRAMPower/commit/da8778b61ae671855c84350af2217b5fdd4472d0#diff-32cd4e872bf7e18e4ab20c4e1842fcd4L231

I apparently replaced the argument of the if-statement with a call to  isLPDDRFamily(), which excluded DDR4. This is clearly wrong.

With regards to LPDDR3 having termination: I am no expert here. I found a comment in the code that says: // LPDDR/2/3 and DDR memories only have IO Power (no ODT). This contradicts the JEDEC spec. The calculations of these numbers is based on some magic numbers in MemorySpecification.h:
https://github.com/ravenrd/DRAMPower/blob/master/src/MemorySpecification.h#L166
Which are in turn based on Micron's power calculation excel sheets.

Any suggestions on what numbers we should plug in for LPDDR3? I currently don't have a massive amount of time to dive into Micron's mobile power calc spreadsheet, so suggestions are welcome.

**Comment by Sv3n** [comment]
As discussed, I've added "LPDDR3 has optional ODT, but it is typically not used (reflections are elimitated by other means (layout))" as a comment in the code. Initially, I planned to add an error in case  the -r flag was given in combination with a memory for which we do not have ODT numbers. However, -r also governs calculation of I/O power based on pin capacitance for the memories that do NOT have ODT, so it actually does something even for them.

We could consider splitting the -r option in two (one for ODT, and one for termination) if desired, but that should be raised as a separate issue, if there is demand for that feature. I'm closing this one.
