### ISSUE TITLE
Does DRAMPower works on MAC OS ?

### ISSUE THREAD

**Issue by ShawnLess** [ravenrd/DRAMPower#29]
I have cloned the latest code and tried to run it my Macbook, but it failed to compile. Following is the error message:
```
bogon:DRAMPower shawnless$ make
g++ -O -W -pedantic-errors -Wextra -Werror -Wformat -Wformat-nonliteral -Wpointer-arith -Wcast-align -Wconversion -Wall -Werror -g   -std=c++0x -MMD -MF src/CmdScheduler.d -iquote src -o src/CmdScheduler.o -c src/CmdScheduler.cc
src/CmdScheduler.cc:87:16: error: implicit conversion changes signedness: 'long long' to 'size_type' (aka 'unsigned long')
      [-Werror,-Wsign-conversion]
  ACT.resize(2 * memSpec.memArchSpec.nbrOfBanks);
  ~~~        ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/CmdScheduler.cc:88:17: error: implicit conversion changes signedness: 'long long' to 'size_type' (aka 'unsigned long')
      [-Werror,-Wsign-conversion]
  RDWR.resize(2 * memSpec.memArchSpec.nbrOfBanks);
```
My OS version is:
```
bogon:DRAMPower shawnless$ uname -a 
Darwin bogon 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```
and my g++ version is:
```
bogon:DRAMPower shawnless$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```
Any suggestion ? Thanks a lot in advance.

**Comment by Sv3n** [comment]
You are in unexplored territory, as far as I know we never tested on mac :). However, looking at the error, I think that you can solve it by replacing line 87 with:

```c++
ACT.resize(static_cast<size_t>(2 * memSpec.memArchSpec.nbrOfBanks));
```

However, there are no guarantees other errors won't appear after you solve this one. Good luck, and if you find / solve any other problems, feel free to let us know.

**Comment by ShawnLess** [comment]
Hi Sven Goossens:

Thanks.  

Yes, this fixed the problem. But there are so many implicit conversions that it is timing consuming to fix all these errors line by line.

Instead of modifying the source code, I deleted the “-Wconversion”  options in the Makefile and the error reduced less than 10.  I think this is equivalent to add “static_cast” operator because  in both method the “Conversion” does happens.

In addition, as I installed the xerces-c through mac port,  I have to change the path of xcerces  and add the xcerces options to gcc  in Makefile.

The attachment is a patch file for  MAC. The modified  code compiled without any warning and  I have test the program  with command "./drampower -m memspecs/MICRON_1Gb_DDR3-1066_8bit_G.xml -t traces/mediabench-epic.trace -r”. The output seemed to be fine. 

I hope this would be helpful.

**Comment by myzinsky** [comment]
Hello,

can you maybe do a pull request?
So I can check the changes on my mac :)

Regards
Matthias


-- 
Dipl.-Ing. Matthias Jung

Member
Advanced Silicon Technologies & Design Methodologies


University of Kaiserslautern
Microelectronic Systems Design Research Group
Erwin-Schrödinger-Straße 12/228
67663 Kaiserslautern, Germany

Phone: +49 631 205 3579
Fax: +49 631 205 4437
jungma@eit.uni-kl.de
http://ems.eit.uni-kl.de

Am 12.02.2016 um 15:47 schrieb ShawnLess:

**Comment by efzulian** [comment]
Hi guys, from the gcc manual, the "-Wconversion" is one among many options to request or suppress warnings. It requests the compiler (g++) to generate warnings for implicit conversions that may alter a value. And "-Werror" tells the compiler to treat warnings as errors.

Not sure if suppressing warnings is the best way to go. They are annoying but their purpose is to show us that something may go wrong in certain circumstances.

IMHO a better approach is to keep the warnings (-Wconversion option) and remove the -Werror flag. It should compile, but with warnings. This is a workaround just to continue working and postpone the real fix to the warnings (by casting or choosing the appropriate signedness (signed or unsigned) to a variable, etc.).

References:
In a terminal
$ man gcc 
or the link below if manpages are not installed
https://gcc.gnu.org/onlinedocs/

Regads,
Éder

**Comment by Sv3n** [comment]
I've made some progress on the mac-compatibility front, on the *mac* branch:

 * I've pulled `CommandScheduler.cc` and `TraceParser.cc` out of `libdrampower.a`, and instead put them in the cli only. This allows us to compile these files with a lower warning level more easily. I started working on  `CommandScheduler.cc` to properly fix the warnings at first, but decided that file is a lost cause...there are too many things that would need to change for it to work properly. Instead, it now compiles without the `-Wconversion` flag.
 * clang compilation is now supported on linux. On my ubuntu machine, I can type `make CXX=clang++-3.6` and get a working compile. Tests work 12/12.
* I've configured travis (our CI system) to build on mac. The build works, but the tests results contain different numbers compared to our reference in 2 out of our 12 tests. I am not sure yet how this happens, especially since my local clang build worked properly. I'll see if I can figure out where the tests begin to diverge.

**Comment by myzinsky** [comment]
I also investigated a little

To run it with MacPorts this has to be changed in the makefile:

```Makefile
XERCES_ROOT ?= /opt/local
...
CXXFLAGS := -O ${WARNFLAGS} ${DBGCXXFLAGS} ${OPTCXXFLAGS} -std=c++0x -I$(XERCES_INC)
...
```

However I'm still not able to compile it even when I remove the Werror and conversion flag i get this message:

```clang
src/CmdScheduler.cc:511:20: error: no matching function for call to 'max'
                   max(0L, memTimingSpec.RTP - 2);
                   ^~~
...
src/CmdScheduler.cc:517:20: error: no matching function for call to 'max'
                   max(memTimingSpec.RTP, 2L) - 2;
                   ^~~
```

**Comment by efzulian** [comment]
Hi Matthias, the std::max() is a function template and my guess is that it requires both parameters to be the same type. Probably your compiler (or this new version you have) does not implicitly assume or convert the types to match and then it can not find any matching signature of the max function, because all the possible signatures require both values to be the same type.

I suggest that you try to use some "static_cast<>" in order to have both values of the same type.
E.g.:
max(0L, static_cast<long int>(memTimingSpec.RTP - 2))

**Comment by Sv3n** [comment]
Or alternatively, clone the `mac` branch that already fixed this particular line if I am not mistaking.

**Comment by myzinsky** [comment]
I think i checked out the Mac branch. I will Check it in the office again later ...

**Comment by efzulian** [comment]
The current top of the master branch (commit hash: 57d46529e00e030ed1c4bbe7ce8368edeffd93a4) is not compiling with gcc-5.2.1 on Linux. The problems are related to type conversions (the error messages can be found in one of the files contained in the zip attached (drampower_test_laptop2)).
Nevertheless, the project compiles without problems when using the mac branch with gcc-5.2.1 (705022fdb9d836513d5f18b4f94e6c310a11debb).

The summary of my tests follow.

Basic tests:
$ make clean && make
$ make test
$ ./drampower -m memspecs/MICRON_1Gb_DDR3-1066_8bit_G.xml -t traces/mediabench epic.trace -r

Results:
gcc-4.8.2 - mac branch - ok (see also: drampower_test_server1)
gcc-4.8.2 - master branch - ok (see also: drampower_test_server2)
gcc-5.2.1 - mac branch - ok (see also: drampower_test_laptop1)
gcc-5.2.1 - master branch - compilation error (see also: drampower_test_laptop2)

[tests_gcc4.8.2_and_gcc5.2.1.zip](https://github.com/ravenrd/DRAMPower/files/228212/tests_gcc4.8.2_and_gcc5.2.1.zip)

**Comment by Sv3n** [comment]
Thanks! That means the mac branch is on the right track, as it seems to fix the known compiler issues.

**Comment by Sv3n** [comment]
The mac branch is now merged into the master branch, and travis automatically tests drampower on a mac machine.

**Comment by efzulian** [comment]
That's great! Thanks Sven. After the merge of the mac branch into the master the compilation of the master branch with gcc/g++-5.2.1 is working properly. The tests from my previous comment are working too. ;)
