### ISSUE TITLE
DRAMPower Library error in calculating intermediate results

### ISSUE THREAD

**Issue by myzinsky** [ravenrd/DRAMPower#31]
We discovered an issue in the DRAMPower library when intermediate results are needed, e.g. to plot the power consumption over time or if an interactive simulation is conducted. Don't worry, the total energy consumption is still correct.

We do a simulation with DRAMSys and want to plot the current power consumption over time:

![bildschirmfoto 2016-04-05 um 09 10 58](https://cloud.githubusercontent.com/assets/1970554/14273941/9018c366-fb0e-11e5-8a03-3c2abbf73aef.png)

at time ~50000 we go into SREF and wake up at ~150000 and we get a big power peak.
in the self refresh time the calculated Energy is 0 and therefore also the current power consumption in the time intervals during SREF.
Obviously the area of this peak should be placed flatted in the interval of the SREF.

This is due to the fact that during the simulation we don’t tell DRAMPower to proceed with the simulation time e.g. during the SREF interval.

I had the idea of a simple workaround:

in our power calculation thread, which is triggered periodically (systemc) I send DRAMPower a NOP function to count up the time:

``` c++
   ...
   // This Thread is only triggered when Power Simulation is enabled (e.g. every 1us).
   // It estimates the current average power which will be stored in the trace database for visualization purposes.
   void powerWindow()
   {
       double currentAveragePower = 0;
       double currentTotalEnergy = 0;

       do
       {              
            unsigned long long c = sc_time_stamp().value()/Configuration::getInstance().memSpec.clk.value();
            DRAMPower->doCommand(MemCommand::NOP, 0, c);
        
           DRAMPower->updateCounters(false);
           DRAMPower->calcEnergy();

           currentTotalEnergy = DRAMPower->getEnergy().total_energy - totalEnergy;
           currentAveragePower = currentTotalEnergy/powerWindowSize.value();
           totalEnergy = DRAMPower->getEnergy().total_energy;

           tlmRecorder->recordPower(sc_time_stamp(),currentAveragePower);
           printDebugMessage(string("\tCurrent Energy: \t") + to_string(currentTotalEnergy));
           printDebugMessage(string("\tAverage Power: \t") + to_string(currentAveragePower));

           wait(powerWindowSize);
       }
       while(true);
   }
   ...
```

However this results in a very strange behavior:

![bildschirmfoto 2016-04-05 um 09 09 06](https://cloud.githubusercontent.com/assets/1970554/14274016/1917953e-fb0f-11e5-80be-578363ec2298.png)

As you can see when we issue multiple NOPs to update the time in DRAM Power, the sref_cycles are accumulating because the beginning of the SREF (sref_cycle) is not updated or reset to the current timestamp.

Lets consider the SREF for now:
``` c++
CommandAnalysis.cc Line 528

  } else if (type == MemCommand::END || type == MemCommand::NOP) {
      // May be optionally used at the end of memory trace for better accuracy
      // Update all counters based on completion of operations.
      if (num_active_banks > 0 && mem_state == 0) {
        actcycles += max(zero, timestamp - first_act_cycle);
        idle_act_update(memSpec, latest_read_cycle, latest_write_cycle,
                        latest_act_cycle, timestamp);
      } else if (num_active_banks == 0 && mem_state == 0) {
        precycles += max(zero, timestamp - last_pre_cycle);
        idle_pre_update(memSpec, timestamp, latest_pre_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_F_ACT) {
        f_act_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_S_ACT) {
        s_act_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_F_PRE) {
        f_pre_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_S_PRE) {
        s_pre_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_SREF) {
        sref_cycles += max(zero, timestamp - sref_cycle); // <—————— this is the possible problem
      }
    }
  }
} // CommandAnalysis::evaluate
```
We changed the code a little bit below:

``` c++
  } else if (type == MemCommand::END || type == MemCommand::NOP) {
      // May be optionally used at the end of memory trace for better accuracy
      // Update all counters based on completion of operations.
      if (num_active_banks > 0 && mem_state == 0) {
        actcycles += max(zero, timestamp - first_act_cycle);
        idle_act_update(memSpec, latest_read_cycle, latest_write_cycle,
                        latest_act_cycle, timestamp);
      } else if (num_active_banks == 0 && mem_state == 0) {
        precycles += max(zero, timestamp - last_pre_cycle);
        idle_pre_update(memSpec, timestamp, latest_pre_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_F_ACT) {
        f_act_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_S_ACT) {
        s_act_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_F_PRE) {
        f_pre_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_PDN_S_PRE) {
        s_pre_pdcycles += max(zero, timestamp - pdn_cycle);
      } else if (mem_state == CommandAnalysis::MS_SREF) {
        sref_cycles += max(zero, timestamp - sref_cycle);
        sref_cycle = timestamp; // RESET the sref_cycle
      }
    }
  }
} // CommandAnalysis::evaluate
```

We did the same for the other power down modes in the else if statements ...
And the result looks like this, which looks much better:

![bildschirmfoto 2016-04-05 um 09 20 26](https://cloud.githubusercontent.com/assets/1970554/14274120/c3447860-fb0f-11e5-8402-ae8f3b3ac97d.png)

We are currently investigating and testing all the changes and we will come up with a pull request soon.
Moreover, we will adjust the library documentation and the example code.

**Comment by efzulian** [comment]
[drampower.patch.zip](https://github.com/ravenrd/DRAMPower/files/207442/drampower.patch.zip)

This is the patch that combined with some changes in DRAMSys solves this issue.

Many thanks to Wendy Elsasser and Radhica Jagtap for their valuable help!

**Comment by Sv3n** [comment]
Hi guys, I've received the mail with the zip / patch. I still need to have a look at it (I'm not on my linux laptop now).

**Comment by efzulian** [comment]
Hi Sven, actually I posted here the patch as a zip file (and some hours later I removed it). It was a mistake, I should have open a proper pull request for that. Please ignore the patch in the zip file for now. We are doing some more tests and as soon we double check everything I will open the pull request.
Thanks!
Éder

**Comment by Sv3n** [comment]
Ok, no problem. I was already confused a bit, since I couldn't find any reference on github to the mail I received :)

**Comment by Sv3n** [comment]
I've merged these changes into the master, and merged the mac branch on top of it. We are now back to a single branch from my perspective (master), which has all the latest features.
